### ISSUE TITLE
datadog measuring seconds or milliseconds?

### ISSUE THREAD

**Issue by jhnlsn** [AppPress/node-connect-datadog#8]
the graphs in datadog are showing that requests are taking 50-300s meaning almost 1minute to over 5 minutes.  I doubt this is correct.  Seems like it's actually measuring milliseconds.  Can someone confirm?

**Comment by respectTheCode** [comment]
We stopped using datadog years ago so I can't say for sure. I know this was working correctly at the time.

**Comment by klausbayrhammer** [comment]
We are seeing the same issue. The datadog docs uses python's time.time() which returns seconds

``` pyhton
start_time = time.time()
results = db.query()
duration = time.time() - start_time
statsd.histogram('database.query.time', duration)
```

**Comment by jhnlsn** [comment]
For anyone with this issue, the fix is to go into Metric -> Summary in your datadog dashboard and locate the `node.express.router.response_time.*` metrics and change the metadata values that say `seconds` to `milliseconds`.  This should change the graphs to represent milliseconds instead of seconds.
